sudo: required
language: python
python:
 - "2.7"
 - "3.3"
 - "3.4"
 - "3.5"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y swig

install:
 - pip install --upgrade setuptools pip
 - pip install -r dev-requirements.txt
 - pip install -e .
script: python -m unittest discover

matrix:
  allow_failures:
    - python: "3.3"
    - python: "3.4"
    - python: "3.5"
