language: python
python:
 - "2.7"
 - "3.3"
 - "3.4"
 - "3.5"
 - "3.6-dev"
 - "nightly"
install:
 - pip install --upgrade setuptools pip
 - pip install -r requirements.txt
 - pip install -r tests-requirements.txt
 - python setup.py develop
script: python setup.py test
notifications:
    email: false
    irc: false
    on_success: change
    on_failure: change
